; PlatformIO Project Configuration File

[base_esp32s3]
platform = espressif32@^6.5.0
board = seeed_xiao_esp32s3
framework = arduino
lib_deps =
	jgromes/RadioLib@^7.4.0
monitor_speed = 115200
build_flags =
	-I lib/RFNet/src
	-std=gnu++17
	-D LOGGER_ENABLED=0
	-D ARDUINO_USB_CDC_ON_BOOT=1

[env:transmitter]
extends = base_esp32s3
build_src_filter =
	+<transmitter/>

[env:receiver]
extends = base_esp32s3
build_src_filter =
	+<receiver/>

[env:node]
extends = base_esp32s3
build_src_filter =
	+<node/>
lib_deps =
	jgromes/RadioLib@^7.4.0
build_flags =
	-I lib/RFNet/src
	-std=gnu++17
	-D LOGGER_ENABLED=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
